### ISSUE TITLE
참고자료 링크

### ISSUE THREAD

**Issue by jiyeon5** [rjhwang08/Clickbait-Classsifier#3]
각자의 참고자료 링크를 쓰시오

**Comment by jiyeon5** [comment]
https://dreamgonfly.github.io/machine/learning,/natural/language/processing/2017/08/16/word2vec_explained.html
:embedding/word2vector설명
https://pythonkim.tistory.com/93
:embedding/word2vector
https://woolulu.tistory.com/132
:embedding_lookup

http://www.wildml.com/2015/12/implementing-a-cnn-for-text-classification-in-tensorflow/
https://ratsgo.github.io/natural%20language%20processing/2017/03/19/CNN/
:cnn을 이용한 문장분류1
http://docs.likejazz.com/cnn-text-classification-tf/
:cnn을 이용한 한국어 문장분류

https://excelsior-cjh.tistory.com/156
:rnn설명
https://excelsior-cjh.tistory.com/185
:brnn한계/gru

https://tensorflowkorea.gitbooks.io/tensorflow-kr/content/g3doc/api_docs/python/array_ops.html
:expand_dims정의

https://eyeofneedle.tistory.com/17
:variable_scope

**Comment by YEJIN325** [comment]
https://m.blog.naver.com/PostView.nhn?blogId=wideeyed&logNo=221343328832&proxyReferer=https%3A%2F%2Fwww.google.com%2F
> tf.nn.embedding_lookup 사용법
https://m.blog.naver.com/PostView.nhn?blogId=wideeyed&logNo=221164750517&proxyReferer=https%3A%2F%2Fwww.google.com%2F
>tf.expand_dims 사용법
https://pythonkim.tistory.com/69
> tf.truncated_normal 사용법
https://eunguru.tistory.com/222
> tf.name_scope 사용법
https://tensorflowkorea.gitbooks.io/tensorflow-kr/content/g3doc/api_docs/python/array_ops.html
> tf.concat 사용법
https://www.tensorflow.org/api_docs/python/tf/nn/l2_loss
> tf.nn.l2_loss 사용법

**Comment by lily0114** [comment]
엑셀 파일 파이썬에서 다루기
1. https://blog.naver.com/engineer1178/221356325425
2. http://pythonstudy.xyz/python/article/405-%ED%8C%8C%EC%9D%B4%EC%8D%AC-%EC%97%91%EC%85%80-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0

공공 인공지능 오픈 API, DATA(언어처리)-어휘 정보/다의어 정보/ 어휘 간 유사도 분석 
http://aiopen.etri.re.kr/guide_wordRel.php

뉴스기사 크롤링+doc2vec 관련 블로그
https://blog.naver.com/gpdlswkd17/221497919363

word2vec
https://dreamgonfly.github.io/machine/learning,/natural/language/processing/2017/08/16/word2vec_explained.html

Embedding Layers
https://towardsdatascience.com/deep-learning-4-embedding-layers-f9a02d55ac12
